Vagrant.configure("2") do |config|

  config.vm.box = "bento/debian-11"

# =============== Server ====================
  config.vm.define "amahlaS" do |server|

# =>  VM settings
    server.vm.hostname = "amahlaS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/"
    server.vm.provision "file", source: "./confs/app1.yaml", destination: "/tmp/"
    server.vm.provision "file", source: "./confs/app2.yaml", destination: "/tmp/"
    server.vm.provision "file", source: "./confs/app3.yaml", destination: "/tmp/"

# =>  Shell file on Buildtime
    server.vm.provision "shell", privileged: true, path: "scripts/script_server.sh"

# =>  Virtualization provider settings
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
      vb.name = "amahlaS"
    end

  end
#  ===============================================

end
