########
######## app app2, sur le domaine "app2.com"
########

---
apiVersion: v1
kind: Namespace
metadata:
  name: app2

---
apiVersion: v1
kind: Service
metadata:
  namespace: app2
  name: app2
  labels:
    app: app2
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: app2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app2
  name: app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: hello-world
        image: tutum/hello-world
        ports:
        - containerPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: app2
  name: app2
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: app2.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app2
            port:
              number: 80
