########
######## app app3, sur le domaine "app3.com"
########

---
apiVersion: v1
kind: Namespace
metadata:
  name: app3

---
apiVersion: v1
kind: Service
metadata:
  namespace: app3
  name: app3
  labels:
    app: app3
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: app3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app3
  name: app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: hello-world
        image: tutum/hello-world
        ports:
        - containerPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: app3
  name: app3
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: app3.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app3
            port:
              number: 80
